=== wagwan-piffting-blud/Speechify_EAS_Listener/doc/ErrorMessages.dtd
<!-- A DTD for SpeechWorks XML error mapping files -->
<!-- Copyright (c) 2001-2003 SpeechWorks International, Inc. -->
<!-- All Rights Reserved -->

<!ENTITY % critical '1'>
<!ENTITY % severe   '2'>
<!ENTITY % warning  '3'>
<!ENTITY % info     '4'>
<!ENTITY % disabled '5'>

<!ELEMENT ErrorMessages (error)* >
<!ATTLIST ErrorMessages version NMTOKEN #FIXED '1.0.0' >
<!ATTLIST ErrorMessages moduleName CDATA #REQUIRED >
<!ELEMENT error (#PCDATA | value-of)* >
<!ATTLIST error num NMTOKEN #REQUIRED >
<!ATTLIST error severity (%critical;|%severe;|%warning;|%info;|%disabled;) #REQUIRED >
<!ELEMENT value-of EMPTY >
<!ATTLIST value-of select CDATA #REQUIRED >

=== wagwan-piffting-blud/Speechify_EAS_Listener/doc/SpeechifyErrors.en-US.xml
<?xml version="1.0" encoding="ISO-8859-1"?>  <!-- XML version -->
<?xml-stylesheet type="text/xsl" href="SpeechifyErrors.xsl"?>

<!-- Speechify configuration file -->
<!-- Copyright (c) 2001-2003 SpeechWorks International, Inc. -->
<!-- All Rights Reserved -->

<!-- Define the structure for the XML -->
<!DOCTYPE ErrorMessages PUBLIC "-//SpeechWorks//DTD ERRORS 1.0//EN"
                        "ErrorMessages.dtd">

<ErrorMessages moduleName="swi:Speechify" version="1.0.0">
    <!-- Speechify client library errors -->
    <error num="1" severity="3">Speechify client return code: The TTS
    client is not initialized </error>
    <error num="2" severity="3">Speechify client return code: One of
    the parameters passed to the function was invalid </error>
    <error num="3" severity="3">Speechify client return code: The
    port handle passed was not a valid handle </error>
    <error num="4" severity="2">Speechify client return code: The
    engine on this port is no longer available </error>
    <error num="5" severity="2">Speechify client return code: An
    internal error occurred in the TTS engine on the server </error>
    <error num="6" severity="1">Speechify client return code: An error
    in the client/server communication occurred</error>
    <error num="7" severity="1">Speechify client return code: WinSock
    initialization failed </error>
    <error num="8" severity="1">Speechify client return code: A
    sockets error occurred </error>
    <error num="9" severity="2">Speechify client return code: The
    client could not connect to the server </error>
    <error num="10" severity="1">Speechify client return code: An
    attempt to allocate memory failed </error>
    <error num="11" severity="1">Speechify client return code: An
    attempt to create a new thread failed </error>
    <error num="12" severity="1">Speechify client return code: An
    attempt to create a new mutex failed </error>
    <error num="13" severity="1">Speechify client return code: An
    error occurred on the server </error>
    <error num="14" severity="1">Speechify client return code: Could
    not resolve the host name or IP address
    </error>
    <error num="15" severity="1">Speechify client return code: A crash
    occurred within the client library. A crash log named ALTmon.dmp
    might have been generated in the Speechify SDK directory. Please
    send it to Speechify technical support. This is an unrecoverable
    error and you should close the application
    </error>
    <error num="16" severity="3">Speechify client return code: This
    API can only be called if the TTS port is idle
    </error>
    <error num="17" severity="3">Speechify client return code: A
    command could not be executed because the port is shutting down
    </error>
    <error num="18" severity="3">Speechify client return code:
    SWIttsClosePort() was called when the port was already being closed
    </error>
    <error num="19" severity="3">Speechify client return code: The
    port is already closed. You cannot invoke SWIttsClosePort() on a
    port that has been closed
    </error>
    <error num="20" severity="3">Speechify client return code: This
    API cannot be executed because another API is in progress on this
    port on another thread
    </error>
    <error num="21" severity="1">Speechify client return code: An
    internal error. Notify ScanSoft technical support if you see
    this result code.
    </error>
    <error num="22" severity="3">Speechify client return code:
    SWIttsStop() was called when the port already in the process of stopping
    </error>
    <error num="23" severity="3">Speechify client return code:
    SWIttsStop() was called when the port was not speaking
    </error>
    <error num="24" severity="3">Speechify client return code:
    SWIttsAddDictionaryEntry() or SWIttsDeleteDictionaryEntry() was
    called with one or more invalid entries
    </error>
    <error num="25" severity="3">Speechify client return code:
    SWIttsSetParameters() was called with at least one read-only parameter
    </error>
    <error num="26" severity="3">Speechify client return code: character
    set is invalid or unsupported
    </error>
    <error num="27" severity="3">Speechify client return code: could not
    parse SSML text
    </error>
    <error num="28" severity="3">Speechify client return code: URI
    fetch failed </error>
    <error num="29" severity="3">Speechify client return code: URI
    fetch failed, URI not found </error>
    <error num="30" severity="3">Speechify client return code: URI
    fetch error, timeout during fetch </error>
    <error num="31" severity="3">Speechify client return code:
    Dictionary operation failed, invalid dictionary type </error>
    <error num="32" severity="3">Speechify client return code:
    Dictionary operation failed, dictionary is active </error>
    <error num="33" severity="3">Speechify client return code:
    Dictionary operation failed, dictionary is not loaded </error>
    <error num="34" severity="3">Speechify client return code:
    Dictionary load failed, dictionary is already loaded </error>
    <error num="35" severity="3">Speechify client return code:
    Dictionary activate failed, another dictionary is already active
    with the specified priority </error>
    <error num="36" severity="3">Speechify client return code:
    Dicationary activate failed, invalid priority </error>
    <error num="37" severity="3">Speechify client return code:
    Dictionary load failed, dictionary parse error </error>
    <error num="38" severity="3">Speechify client return code: API
    failed, no license available </error>
    <error num="39" severity="3">Speechify client return code:
    Resource allocate failed, license already allocated </error>
    <error num="40" severity="3">Speechify client return code:
    Resource free failed, license already freed </error>
    <error num="41" severity="3">Speechify client return code: API
    failed, operation is not supported by the current version of
    Speechify </error>
    <error num="42" severity="3">Speechify client return code:
    SWIttsInit failed, already initialized </error>
    <error num="43" severity="3">Speechify client return code: API
    failed, invalid MIME media type </error>

    <error num="100" severity="1">Speechify client: Internal logic
    error: unknown state </error>
    <error num="101" severity="1">Speechify client: Internal logic
    error: unexpected state </error>
    <error num="102" severity="1">Speechify client: Memory allocation
    failure </error>
    <error num="103" severity="1">Speechify client: OS failure </error>
    <error num="104" severity="1">Speechify client: Fatal TTS engine
    error detected </error>

    <error num="105" severity="2">Speechify client: Transmission error
    detected </error>
    <error num="106" severity="2">Speechify client: Socket function
    failed </error>
    <error num="107" severity="2">Speechify client: Connection lost </error>
    <error num="108" severity="2">Speechify client: Operation timed
    out </error>
    <error num="109" severity="2">Speechify client: Dictionary
    operation completed with errors </error>
    <error num="110" severity="2">Speechify client: Partial speech
    generation failure </error>
    <error num="111" severity="2">Speechify client: SWIttsSpeak:
    server failed to execute a speak request </error>
    <error num="112" severity="2">Speechify client: SWIttsStop: server
    failed to execute a stop request </error>
    <error num="113" severity="2">Speechify client: SWIttsOpen: cannot
    open new port on server </error>

    <error num="114" severity="3">Speechify client: SWIttsClose:
    server could not close port </error>
    <error num="115" severity="3">Speechify client: SWIttsStop:
    attempting to stop when port is not speaking </error>
    <error num="116" severity="3">Speechify client: SWIttsStop: stop
    requested when already stopping </error>
    <error num="117" severity="3">Speechify client: Aborting an
    in-progress operation </error>
    <error num="118" severity="3">Speechify client: Asynchronous API
    is used illegally </error>
    <error num="119" severity="3">Speechify client: SWIttsInit: called
    more than once per process. API call ignored. </error>

    <error num="120" severity="1">Speechify client: Thread or mutex
    failure </error>
    <error num="121" severity="2">Speechify client: Socket operation
    failed </error>
    <error num="122" severity="2">Speechify client: SWIttsOpenPortEx:
    bad parameter list </error>
    <error num="123" severity="2">Speechify client: server cannot
    support this version of the client library </error>
    
    <!-- Main server errors -->
    <error num="1000" severity="2">Speechify server: Failed to
    recieve a request </error>
    <error num="1001" severity="2">Speechify server: Lost the client
    connection </error>
    <error num="1002" severity="2">Speechify server: Socket error
    when waiting for connections </error>
    <error num="1003" severity="1">Speechify server: Could not bind
    to a socket to wait for connections </error>
    <error num="1004" severity="2">Speechify server: Client sent
    unexpected messages after a close port message </error>
    <error num="1005" severity="2">Speechify server: TCP/IP socket
    failure </error>
    <error num="1006" severity="3">Speechify server: Client
    connection rejected, maximum port count exceeded </error>
    <error num="1007" severity="3">Speechify server: Client
    connection rejected, unsupported protocol version </error>
    <error num="1008" severity="2">Speechify server: Client
    connection rejected, did not start with an open message </error>
    <error num="1009" severity="2">Speechify server: Client
    requested an unknown operation </error>
    <error num="1010" severity="3">Speechify server: Could not
    unbind from the socket waiting for connections </error>
